apiVersion: v1
kind: Service
metadata:
  name: argocd-server-temp
  namespace: argocd
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 443
    nodePort: 30090
  selector:
    app.kubernetes.io/name: argocd-server 