apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: impresslola-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wbenhamid77/impressLola.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: impresslola
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10 